# Generated by Django 5.0.1 on 2024-01-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.BigAutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=64)),
                ('prenume', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('telefon', models.CharField(max_length=64)),
                ('cnp', models.CharField(max_length=64)),
                ('adresa', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Avocat',
            fields=[
                ('id_avocat', models.BigAutoField(primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=64)),
                ('prenume', models.CharField(max_length=64)),
                ('telefon', models.CharField(max_length=64)),
                ('cnp', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('specializare', models.CharField(max_length=64)),
                ('speta', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'avocat',
            },
        ),
    ]
