# Generated by Django 5.0.1 on 2024-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id_contract', models.BigAutoField(primary_key=True, serialize=False)),
                ('valoare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_start', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('judecatorie', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'contract',
                'managed': False,
            },
        ),
    ]
